#!/usr/bin/env -S csi -s

(load "alist-let.scm")

(print "Fixnum keys")
(alist-let = '((0 . 1) (2 . 3) (4 . 5))
           ((a 0) (b 2) (c 4) (d 6 42))
           (print "a: " a)
           (print "b: " b)
           (print "c: " c)
           (print "d: " d))
(newline)

(print "Symbol keys")
(alist-let eq? '((a . 1) (b . 3) (c . 5))
           ((a 'a) (b 'b) (c 'c) (d 'd 42))
           (print "a: " a)
           (print "b: " b)
           (print "c: " c)
           (print "d: " d))
(newline)

(print "String keys")
(alist-let string=? '(("a" . 1) ("b" . 3) ("c" . 5))
           ((a "a" #f) (b "b" #f) (c "c" #f) (d "d" 42))
           (print "a: " a)
           (print "b: " b)
           (print "c: " c)
           (print "d: " d))
(newline)

(print "String keys (w/ duplicate keys)")
(alist-let string=? '(("a" . 1) ("a" . 2) ("b" . 4)) ((a1 "a") (a2 "a") (a3 "a"))
  (print "a1: " a1)
  (print "a2: " a2)
  (print "a3: " a3))
(newline)
